from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

BRAND_PURPLE = colors.HexColor("#5b4bd1")
SLATE_700 = colors.HexColor("#334155")
SLATE_500 = colors.HexColor("#64748b")
SLATE_100 = colors.HexColor("#f1f5f9")

styles = getSampleStyleSheet()
STYLE_HOSPITAL_NAME = ParagraphStyle(
    "HospitalName", parent=styles["Heading1"], fontSize=18, textColor=BRAND_PURPLE, spaceAfter=0
)
STYLE_DOC_TITLE = ParagraphStyle(
    "DocTitle", parent=styles["Normal"], fontSize=11, textColor=SLATE_500, alignment=2
)
STYLE_SECTION = ParagraphStyle(
    "Section", parent=styles["Heading3"], fontSize=11, textColor=BRAND_PURPLE, spaceBefore=12, spaceAfter=4
)
STYLE_BODY = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, textColor=SLATE_700, leading=14)
STYLE_LABEL = ParagraphStyle("Label", parent=styles["Normal"], fontSize=8, textColor=SLATE_500)
STYLE_VALUE = ParagraphStyle("Value", parent=styles["Normal"], fontSize=10, textColor=SLATE_700)
STYLE_FOOTER = ParagraphStyle(
    "Footer", parent=styles["Normal"], fontSize=9, textColor=SLATE_500, alignment=1
)
STYLE_DISCLAIMER = ParagraphStyle(
    "Disclaimer", parent=styles["Normal"], fontSize=8, textColor=SLATE_500, leading=11
)
STYLE_TABLE_CELL = ParagraphStyle(
    "TableCell", parent=styles["Normal"], fontSize=9, textColor=SLATE_700, leading=12
)


def _age_from_dob(dob):
    if not dob:
        return None
    today = date.today()
    return today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))


def _info_row(label, value):
    return [Paragraph(label.upper(), STYLE_LABEL), Paragraph(value or "—", STYLE_VALUE)]


def generate_consultation_pdf(consultation, output_path):
    """Renders a consultation's summary into a hospital-letterhead-style PDF."""
    patient = consultation.patient
    doctor = consultation.doctor
    summary = consultation.summary
    prescriptions = consultation.prescriptions

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
    )
    story = []

    # --- Header -----------------------------------------------------------
    header = Table(
        [[Paragraph("YASODHA HOSPITALS", STYLE_HOSPITAL_NAME), Paragraph("Consultation Report", STYLE_DOC_TITLE)]],
        colWidths=[100 * mm, 70 * mm],
    )
    header.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "BOTTOM")]))
    story.append(header)
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", color=SLATE_100, thickness=1))
    story.append(Spacer(1, 10))

    # --- Patient / visit info ----------------------------------------------
    age = _age_from_dob(patient.dob) if patient else None
    age_gender = " / ".join(
        filter(None, [str(age) if age is not None else None, (patient.gender or "").capitalize() if patient else None])
    )
    visit_date = consultation.started_at.strftime("%B %d, %Y") if consultation.started_at else "—"

    info_table = Table(
        [
            _info_row("Patient Name", patient.name if patient else "—")
            + _info_row("Doctor", doctor.user.name if doctor and doctor.user else "—"),
            _info_row("Age / Gender", age_gender or "—")
            + _info_row("Department", doctor.department.name if doctor and doctor.department else "—"),
            _info_row("Patient ID", f"PAT{patient.id:04d}" if patient else "—")
            + _info_row("Date", visit_date),
        ],
        colWidths=[35 * mm, 55 * mm, 35 * mm, 55 * mm],
    )
    info_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(info_table)
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", color=SLATE_100, thickness=1))

    # --- Clinical summary ---------------------------------------------------
    story.append(Paragraph("Clinical Summary", STYLE_SECTION))
    story.append(Paragraph(summary.summary or "—", STYLE_BODY))

    if summary.symptoms:
        story.append(Paragraph("Symptoms", STYLE_SECTION))
        story.append(Paragraph(summary.symptoms, STYLE_BODY))

    story.append(Paragraph("Possible Diagnosis (Assistive)", STYLE_SECTION))
    story.append(Paragraph(summary.possible_diagnosis or "—", STYLE_BODY))
    story.append(
        Paragraph(
            "Assistive only — generated by AI from the consultation transcript, not a confirmed "
            "diagnosis. Verified and issued under the treating doctor's supervision.",
            STYLE_DISCLAIMER,
        )
    )

    # --- Prescription --------------------------------------------------------
    story.append(Paragraph("Prescription", STYLE_SECTION))
    if prescriptions:
        rows = [["Medicine", "Dose", "Frequency", "Duration"]]
        for p in prescriptions:
            rows.append(
                [
                    Paragraph(p.medicine_name, STYLE_TABLE_CELL),
                    Paragraph(p.dose or "—", STYLE_TABLE_CELL),
                    Paragraph(p.frequency or "—", STYLE_TABLE_CELL),
                    Paragraph(p.duration or "—", STYLE_TABLE_CELL),
                ]
            )
        rx_table = Table(rows, colWidths=[40 * mm, 25 * mm, 65 * mm, 40 * mm])
        rx_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), SLATE_100),
                    ("TEXTCOLOR", (0, 0), (-1, 0), SLATE_500),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("LINEBELOW", (0, 0), (-1, 0), 0.5, SLATE_100),
                    ("LINEBELOW", (0, 1), (-1, -1), 0.5, SLATE_100),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("TEXTCOLOR", (0, 1), (-1, -1), SLATE_700),
                ]
            )
        )
        story.append(rx_table)
    else:
        story.append(Paragraph("No medicines prescribed.", STYLE_BODY))

    # --- Advice ----------------------------------------------------------------
    if summary.follow_up_advice:
        story.append(Paragraph("Follow-up Advice", STYLE_SECTION))
        items = [ListItem(Paragraph(a, STYLE_BODY)) for a in summary.follow_up_advice.splitlines() if a]
        story.append(ListFlowable(items, bulletType="bullet", start="•"))

    if summary.lifestyle_advice:
        story.append(Paragraph("Lifestyle Advice", STYLE_SECTION))
        items = [ListItem(Paragraph(a, STYLE_BODY)) for a in summary.lifestyle_advice.splitlines() if a]
        story.append(ListFlowable(items, bulletType="bullet", start="•"))

    # --- Signature / footer -----------------------------------------------------
    story.append(Spacer(1, 24))
    doctor_name = doctor.user.name if doctor and doctor.user else "—"
    doctor_spec = doctor.specialization if doctor else ""
    reg_no = doctor.registration_no if doctor else ""
    sig_lines = [doctor_name]
    if doctor_spec:
        sig_lines.append(doctor_spec)
    if reg_no:
        sig_lines.append(f"Reg. No. {reg_no}")
    sig_table = Table(
        [[Paragraph("<br/>".join(sig_lines), ParagraphStyle("Sig", parent=STYLE_BODY, alignment=2))]],
        colWidths=[170 * mm],
    )
    story.append(sig_table)

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", color=SLATE_100, thickness=1))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Thank you for choosing Yasodha Hospitals", STYLE_FOOTER))

    doc.build(story)
    return output_path
