"""emergency cases

Revision ID: 20018e2c1e68
Revises: c9d4e1f8a3b7
Create Date: 2026-08-12 12:48:18.024220

A second, lightweight entry point alongside the OP queue for a patient whose
treatment cannot wait for one -- `create_appointment` requires an assigned
doctor and a matching department, which an emergency arrival never has yet.
Reception logs the case, any on-duty doctor claims it (`doctor_id`, unassigned
until then, exactly like `appointments.doctor_id`), and works from
`assessment_notes` / `treatment_notes` / `decision` directly on this row --
not a Consultation, which cannot be closed without a recorded conversation.

Claiming does not touch `patients.assigned_doctor_id`; access is instead
scoped to the open case (see `helpers/patient_access.has_active_emergency_claim`),
so a patient's regular doctor is never displaced by whoever handled their
emergency. `linked_appointment_id` / `linked_consultation_id` connect the
episode to whatever normal OP or consultation eventually follows it.

Also widens `nursing_assignments.care_type` to add `icu`, alongside the
existing `observation` -- both are already used for emergency-triggered
assignments made with no surgery pathway and no consultation involved (see
the additive gate in `nursing_routes.create_assignment`). Purely additive:
the four existing values are untouched.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20018e2c1e68'
down_revision = 'c9d4e1f8a3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'serious', 'stable', name='emergency_case_severity'), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'in_progress', 'resolved', 'cancelled', name='emergency_case_status'), nullable=False),
    sa.Column('decision', sa.Enum('ot_surgery', 'icu', 'observation', 'discharge', 'other', name='emergency_case_decision'), nullable=True),
    sa.Column('arrived_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('treatment_notes', sa.Text(), nullable=True),
    sa.Column('linked_appointment_id', sa.Integer(), nullable=True),
    sa.Column('linked_consultation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['linked_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['linked_consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.create_index('idx_emergency_cases_status_severity', ['status', 'severity'], unique=False)

    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.alter_column('care_type',
               existing_type=mysql.ENUM('observation', 'post_surgery', 'post_procedure', 'recovery'),
               type_=sa.Enum('observation', 'post_surgery', 'post_procedure', 'recovery', 'icu', name='nursing_care_type'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.alter_column('care_type',
               existing_type=sa.Enum('observation', 'post_surgery', 'post_procedure', 'recovery', 'icu', name='nursing_care_type'),
               type_=mysql.ENUM('observation', 'post_surgery', 'post_procedure', 'recovery'),
               existing_nullable=False)

    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.drop_index('idx_emergency_cases_status_severity')

    op.drop_table('emergency_cases')
    # ### end Alembic commands ###
