"""care messages and audit detail

Revision ID: 2109b41bae74
Revises: 4cdff1fe7bd9
Create Date: 2026-07-31 18:40:42.514585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2109b41bae74'
down_revision = '4cdff1fe7bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.Enum('doctor', 'nurse', 'admin', name='care_message_sender'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['nursing_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_messages', schema=None) as batch_op:
        batch_op.create_index('idx_care_messages_assignment_created', ['assignment_id', 'created_at'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.String(length=255), nullable=True))
        batch_op.create_index('idx_audit_entity', ['entity', 'entity_id', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user_created')
        batch_op.drop_index('idx_audit_entity')
        batch_op.drop_column('detail')
        batch_op.drop_column('actor_role')

    with op.batch_alter_table('care_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_care_messages_assignment_created')

    op.drop_table('care_messages')
    # ### end Alembic commands ###
