"""patient doctor assignment

Revision ID: 214f1dfc5a67
Revises: 8aabb079b811
Create Date: 2026-07-30 16:41:19.070249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214f1dfc5a67'
down_revision = '8aabb079b811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'doctors', ['assigned_doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_doctor_id')

    # ### end Alembic commands ###
