"""widen prescription and medicine text columns

Revision ID: 223494f9e36d
Revises: be84ea26bf16
Create Date: 2026-07-30 02:36:56.012462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '223494f9e36d'
down_revision = 'be84ea26bf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_prescriptions', schema=None) as batch_op:
        batch_op.alter_column('dose',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('frequency',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('default_dose',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('default_frequency',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('default_frequency',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
        batch_op.alter_column('default_dose',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('generated_prescriptions', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
        batch_op.alter_column('dose',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
