"""staff registration requests

Revision ID: 2a6b30d5fb14
Revises: de542e716f50
Create Date: 2026-08-04 10:43:37.282331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6b30d5fb14'
down_revision = 'de542e716f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('requested_role', sa.Enum('doctor', 'nurse', 'receptionist', 'pharmacist', name='requested_role'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('license_no', sa.String(length=60), nullable=True),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='registration_status'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.String(length=255), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.create_index('idx_registration_email', ['email'], unique=False)
        batch_op.create_index('idx_registration_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_registration_status_created')
        batch_op.drop_index('idx_registration_email')

    op.drop_table('registration_requests')
    # ### end Alembic commands ###
