"""laboratory test requests and discussion

Creates `lab_requests` (a doctor's test order and its result) and
`lab_messages` (the discussion and status history for one such order).

`lab_messages` cascades from `lab_requests` so a deleted order takes its
thread with it — a conversation about a test that no longer exists has
nothing to be attached to, which is the property that keeps this from
being a general chat store.

Autogenerate again proposed dropping four unrelated indexes on
clinical_precedents, custom_medicine_requests, medicine_departments and
patient_cases. That is pre-existing model/database drift, nothing to do
with the laboratory, and it has been removed here for the same reason as
in 4c7ce7a093f0.

Revision ID: 347ea7cf65c7
Revises: 4c7ce7a093f0
Create Date: 2026-08-07 15:33:31.001446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347ea7cf65c7'
down_revision = '4c7ce7a093f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('test_category', sa.String(length=100), nullable=True),
    sa.Column('specimen', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('routine', 'urgent', name='lab_priority'), server_default='routine', nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ordered', 'sample_collected', 'processing', 'completed', 'verified', 'cancelled', name='lab_status'), server_default='ordered', nullable=False),
    sa.Column('recollection_requested', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('recollection_reason', sa.String(length=500), nullable=True),
    sa.Column('recollection_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('report_file', sa.String(length=255), nullable=True),
    sa.Column('report_original_name', sa.String(length=255), nullable=True),
    sa.Column('report_uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.create_index('idx_lab_doctor_status', ['doctor_id', 'status'], unique=False)
        batch_op.create_index('idx_lab_patient_created', ['patient_id', 'created_at'], unique=False)
        batch_op.create_index('idx_lab_technician_status', ['technician_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_consultation_id'), ['consultation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_technician_id'), ['technician_id'], unique=False)

    op.create_table('lab_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('message', 'system', name='lab_message_kind'), server_default='message', nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_request_id'], ['lab_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_messages_lab_request_id'), ['lab_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_messages_lab_request_id'))

    op.drop_table('lab_messages')
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_requests_technician_id'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_consultation_id'))
        batch_op.drop_index('idx_lab_technician_status')
        batch_op.drop_index('idx_lab_patient_created')
        batch_op.drop_index('idx_lab_doctor_status')

    op.drop_table('lab_requests')
    # ### end Alembic commands ###
