"""patient assignment notification category

Revision ID: 4ab5d2777db5
Revises: 20018e2c1e68
Create Date: 2026-08-12 15:54:57.832761

A doctor previously got no notification at all when a patient was registered
or routed to them -- `create_patient` and `reassign_patient` sent nothing.
Purely additive: the seven existing values are untouched, so nothing that
already reads or writes a notification's category changes.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ab5d2777db5'
down_revision = '20018e2c1e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.ENUM('appointment', 'consultation', 'report', 'nursing', 'pharmacy', 'shift', 'system'),
               type_=sa.Enum('appointment', 'consultation', 'report', 'nursing', 'patient_assignment', 'pharmacy', 'shift', 'system', name='notification_category'),
               existing_nullable=False,
               existing_server_default=sa.text("'system'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('appointment', 'consultation', 'report', 'nursing', 'patient_assignment', 'pharmacy', 'shift', 'system', name='notification_category'),
               type_=mysql.ENUM('appointment', 'consultation', 'report', 'nursing', 'pharmacy', 'shift', 'system'),
               existing_nullable=False,
               existing_server_default=sa.text("'system'"))

    # ### end Alembic commands ###
