"""microsecond precision on nursing timestamps

Revision ID: 5779cd74729c
Revises: 80cbbff49c70
Create Date: 2026-08-03 11:05:14.796125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5779cd74729c'
down_revision = '80cbbff49c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('medication_orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('nursing_notes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('patient_observations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_observations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('nursing_notes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('medication_orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('care_messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP().with_variant(mysql.DATETIME(fsp=6), 'mysql'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###
