"""prescription verification

Revision ID: 8aabb079b811
Revises: 17e7ac148b6a
Create Date: 2026-07-30 15:33:54.953200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aabb079b811'
down_revision = '17e7ac148b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prescription_verified_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['prescription_verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prescription_verified_by')
        batch_op.drop_column('prescription_verified_at')

    # ### end Alembic commands ###
