"""nursing doctor review marker

Revision ID: a5752d1b80ce
Revises: 2109b41bae74
Create Date: 2026-08-03 10:29:15.802776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5752d1b80ce'
down_revision = '2109b41bae74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_seen_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.drop_column('doctor_seen_at')

    # ### end Alembic commands ###
