"""staff management: profiles and new roles

Revision ID: a60fe0859833
Revises: 9a51dd64f4ba
Create Date: 2026-08-04 11:18:59.789092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60fe0859833'
down_revision = '9a51dd64f4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='staff_gender'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('registration_no', sa.String(length=60), nullable=True),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('shift', sa.Enum('morning', 'evening', 'night', name='staff_shift'), nullable=True),
    sa.Column('lab_department', sa.String(length=120), nullable=True),
    sa.Column('qualification', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_staff_employee_code', ['employee_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_staff_employee_code')

    op.drop_table('staff_profiles')
    # ### end Alembic commands ###
