"""add patient op_status and last_registered_at

Revision ID: b21f6da532d5
Revises: 7d89c3434412
Create Date: 2026-07-30 17:21:05.506451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21f6da532d5'
down_revision = '7d89c3434412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('op_status', sa.Enum('free', 'paid', name='op_status'), nullable=True))
        batch_op.add_column(sa.Column('last_registered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('last_registered_at')
        batch_op.drop_column('op_status')

    # ### end Alembic commands ###
