"""speaker unknown and labeled transcript

Revision ID: be84ea26bf16
Revises: 17d2c289dc0a
Create Date: 2026-07-30 02:15:30.868534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be84ea26bf16'
down_revision = '17d2c289dc0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labeled_transcript', sa.Text(), nullable=True))

    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.alter_column('speaker',
               existing_type=mysql.ENUM('doctor', 'patient', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('doctor', 'patient', 'unknown', name='message_speaker'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.alter_column('speaker',
               existing_type=sa.Enum('doctor', 'patient', 'unknown', name='message_speaker'),
               type_=mysql.ENUM('doctor', 'patient', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    with op.batch_alter_table('consultation_summaries', schema=None) as batch_op:
        batch_op.drop_column('labeled_transcript')

    # ### end Alembic commands ###
