"""remove patient op_status and last_registered_at

Revision ID: c4594dbb6cf2
Revises: b21f6da532d5
Create Date: 2026-07-30 17:35:01.742346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4594dbb6cf2'
down_revision = 'b21f6da532d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('last_registered_at')
        batch_op.drop_column('op_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('op_status', mysql.ENUM('free', 'paid', collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('last_registered_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
