"""nursing module

Revision ID: cc97ad825465
Revises: 73d826fd9a04
Create Date: 2026-07-31 10:42:19.700522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc97ad825465'
down_revision = '73d826fd9a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_no', sa.String(length=50), nullable=True),
    sa.Column('shift', sa.Enum('morning', 'evening', 'night', name='nurse_shift'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('nursing_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('care_type', sa.Enum('observation', 'post_surgery', 'post_procedure', 'recovery', name='nursing_care_type'), nullable=False),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='nursing_assignment_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_nursing_assignments_doctor_status', ['doctor_id', 'status'], unique=False)
        batch_op.create_index('idx_nursing_assignments_nurse_status', ['nurse_id', 'status'], unique=False)

    op.create_table('clinical_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('emergency', 'missed_medication', 'abnormal_observation', 'critical_change', 'other', name='clinical_alert_category'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='clinical_alert_severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='clinical_alert_status'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('doctor_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignment_id'], ['nursing_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_clinical_alerts_doctor_status', ['doctor_id', 'status', 'created_at'], unique=False)

    op.create_table('medication_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('route', sa.Enum('oral', 'injection', 'iv', 'topical', 'inhalation', 'other', name='medication_route'), nullable=False),
    sa.Column('dose', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['nursing_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nursing_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.Enum('note', 'handover', name='nursing_note_type'), nullable=False),
    sa.Column('shift', sa.Enum('morning', 'evening', 'night', name='nursing_note_shift'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('handover_to_nurse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['nursing_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handover_to_nurse_id'], ['nurses.id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nursing_notes', schema=None) as batch_op:
        batch_op.create_index('idx_nursing_notes_assignment_created', ['assignment_id', 'created_at'], unique=False)

    op.create_table('patient_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('pulse_bpm', sa.Integer(), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('blood_sugar', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('recovery_progress', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['nursing_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_observations', schema=None) as batch_op:
        batch_op.create_index('idx_observations_assignment_recorded', ['assignment_id', 'recorded_at'], unique=False)

    op.create_table('medication_administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('route', sa.Enum('oral', 'injection', 'iv', 'topical', 'inhalation', 'other', name='medication_route'), nullable=False),
    sa.Column('dose', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('administered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('completed', 'delayed', 'missed', 'skipped', name='medication_admin_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['nursing_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['medication_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.create_index('idx_med_admin_assignment_created', ['assignment_id', 'created_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.ENUM('appointment', 'consultation', 'report', 'system', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('appointment', 'consultation', 'report', 'nursing', 'system', name='notification_category'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('appointment', 'consultation', 'report', 'nursing', 'system', name='notification_category'),
               type_=mysql.ENUM('appointment', 'consultation', 'report', 'system', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.drop_index('idx_med_admin_assignment_created')

    op.drop_table('medication_administrations')
    with op.batch_alter_table('patient_observations', schema=None) as batch_op:
        batch_op.drop_index('idx_observations_assignment_recorded')

    op.drop_table('patient_observations')
    with op.batch_alter_table('nursing_notes', schema=None) as batch_op:
        batch_op.drop_index('idx_nursing_notes_assignment_created')

    op.drop_table('nursing_notes')
    op.drop_table('medication_orders')
    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_clinical_alerts_doctor_status')

    op.drop_table('clinical_alerts')
    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_nursing_assignments_nurse_status')
        batch_op.drop_index('idx_nursing_assignments_doctor_status')

    op.drop_table('nursing_assignments')
    op.drop_table('nurses')
    # ### end Alembic commands ###
