"""pharmacy: branches, pharmacists, medicine brands and stock

Revision ID: de542e716f50
Revises: 5b63d5d17064
Create Date: 2026-08-04 10:27:16.780035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de542e716f50'
down_revision = '5b63d5d17064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('medicine_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('generic_name', sa.String(length=150), nullable=True),
    sa.Column('used_for', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('form', sa.Enum('tablet', 'capsule', 'syrup', 'injection', 'iv_fluid', 'ointment', 'drops', 'inhaler', 'sachet', 'other', name='medicine_form'), nullable=False),
    sa.Column('strength', sa.String(length=80), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_name', 'strength', name='uq_brand_strength')
    )
    with op.batch_alter_table('medicine_brands', schema=None) as batch_op:
        batch_op.create_index('idx_brand_name', ['brand_name'], unique=False)

    op.create_table('pharmacists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('license_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('stock_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=60), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['medicine_brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.create_index('idx_stock_branch_brand', ['branch_id', 'brand_id'], unique=False)
        batch_op.create_index('idx_stock_expiry', ['expiry_date'], unique=False)

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_column('draft_error')
        batch_op.drop_column('draft_result')
        batch_op.drop_column('draft_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_status', mysql.ENUM('pending', 'ready', 'failed', collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('draft_result', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('draft_error', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))

    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_expiry')
        batch_op.drop_index('idx_stock_branch_brand')

    op.drop_table('stock_batches')
    op.drop_table('pharmacists')
    with op.batch_alter_table('medicine_brands', schema=None) as batch_op:
        batch_op.drop_index('idx_brand_name')

    op.drop_table('medicine_brands')
    op.drop_table('branches')
    # ### end Alembic commands ###
