"""re-add patient op_status and last_registered_at

Revision ID: fba096ffbcc8
Revises: c4594dbb6cf2
Create Date: 2026-07-30 17:54:25.268879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba096ffbcc8'
down_revision = 'c4594dbb6cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('op_status', sa.Enum('free', 'paid', name='op_status'), nullable=True))
        batch_op.add_column(sa.Column('last_registered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('last_registered_at')
        batch_op.drop_column('op_status')

    # ### end Alembic commands ###
